### ISSUE TITLE
runtime error: invalid memory 

### ISSUE THREAD

**Issue by Hsuing** [eyebluecn/tank-front#11]
第一天没有问题
第二天登陆的时候报以下错误，并且第一天上传的东西不显示了
runtime error: invalid memory address or nil pointer dereference

**Comment by seaheart** [comment]
你好，考虑到有可能是服务器环境出现了问题，也可能可能数据库文件被删了，磁盘满了

**Comment by Hsuing** [comment]
好的，后期可以添加一个删除用户的功能
