### ISSUE TITLE
Video playback problems

### ISSUE THREAD

**Issue by gemone** [eyebluecn/tank-front#19]
This is a feature recommendation.
I tried to use the online disc to play online, but I found that the content was downloaded directly. Is there a problem with the preview? Or is the video preview format limited?
Video format for. WMV.
We hope to increase the video preview. This function can be turned on and off for users with traffic.
Hope the program is getting better and better.

**Comment by zhaojh329** [comment]
无法访问特殊文件名，例如#
![image](https://user-images.githubusercontent.com/28673295/82754049-f40c7d00-9dfc-11ea-9d9c-c9f2f37e4513.png)

**Comment by seaheart** [comment]
hi，the version (greater than 3.1.0) can configure the custom preview engine in preference. [](https://tank-doc.eyeblue.cn/advance/preview.html)

**Comment by seaheart** [comment]
https://tank-doc.eyeblue.cn/advance/preview.html
