### ISSUE TITLE
编译前端出问题

### ISSUE THREAD

**Issue by Zynismus16** [eyebluecn/tank-front#31]
配置好环境后运行 npm run build 提示
`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tank-front@3.1.2 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tank-front@3.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-11T05_53_44_135Z-debug.log
`
完整代码如下 非常喜欢大大的程序，希望能够指正我的问题 谢谢
`root@vmi520813:/www/wwwroot/tank-front# npm run build

> tank-front@3.1.2 build /www/wwwroot/tank-front
> node scripts/build.js

/www/wwwroot/tank-front/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
    at validate (/www/wwwroot/tank-front/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new TerserPlugin (/www/wwwroot/tank-front/node_modules/terser-webpack-plugin/dist/index.js:116:31)
    at module.exports (/www/wwwroot/tank-front/config/webpack.config.js:196:9)
    at Object.<anonymous> (/www/wwwroot/tank-front/scripts/build.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: { additionalProperty: 'sourceMap' },
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: {
        definitions: {
          Rule: {
            description: 'Filtering rule as regex or string.',
            anyOf: [Array]
          },
          Rules: { description: 'Filtering rules.', anyOf: [Array] }
        },
        title: 'TerserPluginOptions',
        type: 'object',
        additionalProperties: false,
        properties: {
          test: {
            description: 'Include all modules that pass test assertion.',
            oneOf: [Array]
          },
          include: {
            description: 'Include all modules matching any of these conditions.',
            oneOf: [Array]
          },
          exclude: {
            description: 'Exclude all modules matching any of these conditions.',
            oneOf: [Array]
          },
          terserOptions: {
            description: 'Options for `terser`.',
            additionalProperties: true,
            type: 'object'
          },
          extractComments: {
            description: 'Whether comments shall be extracted to a separate file.',
            anyOf: [Array]
          },
          parallel: {
            description: 'Use multi-process parallel running to improve the build speed.',
            anyOf: [Array]
          },
          minify: {
            description: 'Allows you to override default minify function.',
            instanceof: 'Function'
          }
        },
        default: {
          definitions: { Rule: [Object], Rules: [Object] },
          title: 'TerserPluginOptions',
          type: 'object',
          additionalProperties: false,
          properties: {
            test: [Object],
            include: [Object],
            exclude: [Object],
            terserOptions: [Object],
            extractComments: [Object],
            parallel: [Object],
            minify: [Object]
          }
        }
      },
      data: {
        terserOptions: {
          parse: { ecma: 8 },
          compress: {
            ecma: 5,
            warnings: false,
            comparisons: false,
            inline: 2,
            keep_fnames: true
          },
          mangle: { safari10: true, keep_fnames: true },
          keep_classnames: false,
          keep_fnames: false,
          output: { ecma: 5, comments: false, ascii_only: true }
        },
        sourceMap: true
      }
    }
  ],
  schema: {
    definitions: {
      Rule: {
        description: 'Filtering rule as regex or string.',
        anyOf: [
          { instanceof: 'RegExp', tsType: 'RegExp' },
          { type: 'string', minLength: 1 }
        ]
      },
      Rules: {
        description: 'Filtering rules.',
        anyOf: [
          { type: 'array', items: [Object] },
          { '$ref': '#/definitions/Rule' }
        ]
      }
    },
    title: 'TerserPluginOptions',
    type: 'object',
    additionalProperties: false,
    properties: {
      test: {
        description: 'Include all modules that pass test assertion.',
        oneOf: [ { '$ref': '#/definitions/Rules' } ]
      },
      include: {
        description: 'Include all modules matching any of these conditions.',
        oneOf: [ { '$ref': '#/definitions/Rules' } ]
      },
      exclude: {
        description: 'Exclude all modules matching any of these conditions.',
        oneOf: [ { '$ref': '#/definitions/Rules' } ]
      },
      terserOptions: {
        description: 'Options for `terser`.',
        additionalProperties: true,
        type: 'object'
      },
      extractComments: {
        description: 'Whether comments shall be extracted to a separate file.',
        anyOf: [
          { type: 'boolean' },
          { type: 'string', minLength: 1 },
          { instanceof: 'RegExp' },
          { instanceof: 'Function' },
          {
            additionalProperties: false,
            properties: [Object],
            type: 'object'
          }
        ]
      },
      parallel: {
        description: 'Use multi-process parallel running to improve the build speed.',
        anyOf: [ { type: 'boolean' }, { type: 'integer' } ]
      },
      minify: {
        description: 'Allows you to override default minify function.',
        instanceof: 'Function'
      }
    },
    default: {
      definitions: {
        Rule: {
          description: 'Filtering rule as regex or string.',
          anyOf: [ [Object], [Object] ]
        },
        Rules: {
          description: 'Filtering rules.',
          anyOf: [ [Object], [Object] ]
        }
      },
      title: 'TerserPluginOptions',
      type: 'object',
      additionalProperties: false,
      properties: {
        test: {
          description: 'Include all modules that pass test assertion.',
          oneOf: [ [Object] ]
        },
        include: {
          description: 'Include all modules matching any of these conditions.',
          oneOf: [ [Object] ]
        },
        exclude: {
          description: 'Exclude all modules matching any of these conditions.',
          oneOf: [ [Object] ]
        },
        terserOptions: {
          description: 'Options for `terser`.',
          additionalProperties: true,
          type: 'object'
        },
        extractComments: {
          description: 'Whether comments shall be extracted to a separate file.',
          anyOf: [ [Object], [Object], [Object], [Object], [Object] ]
        },
        parallel: {
          description: 'Use multi-process parallel running to improve the build speed.',
          anyOf: [ [Object], [Object] ]
        },
        minify: {
          description: 'Allows you to override default minify function.',
          instanceof: 'Function'
        }
      }
    }
  },
  headerName: 'Terser Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tank-front@3.1.2 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tank-front@3.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-11T05_53_44_135Z-debug.log
`

**Comment by Zynismus16** [comment]
这是日志文件
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.11
3 info using node@v12.21.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle tank-front@3.1.2~prebuild: tank-front@3.1.2
6 info lifecycle tank-front@3.1.2~build: tank-front@3.1.2
7 verbose lifecycle tank-front@3.1.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle tank-front@3.1.2~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/wwwroot/tank-front/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle tank-front@3.1.2~build: CWD: /www/wwwroot/tank-front
10 silly lifecycle tank-front@3.1.2~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle tank-front@3.1.2~build: Returned: code: 1  signal: null
12 info lifecycle tank-front@3.1.2~build: Failed to exec build script
13 verbose stack Error: tank-front@3.1.2 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid tank-front@3.1.2
15 verbose cwd /www/wwwroot/tank-front
16 verbose Linux 4.15.0-135-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.21.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error tank-front@3.1.2 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the tank-front@3.1.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by Rabbit0w0** [comment]
下载release就好了

**Comment by zicla** [comment]
3.1.4版本对前端进行升级，下载再重新试一下应该可以了
