### ISSUE TITLE
如何在本地运行前端项目后进入云盘

### ISSUE THREAD

**Issue by donghaina** [eyebluecn/tank-front#4]
我下载了您的代码，在本地`npm run  dev`之后用体验账号： demo@tank.eyeblue.cn 密码：123456试图登录看云盘里边的东西，但是并不能登录，有没有一个可以用来只看前端的账号呢。

**Comment by BobHongYuChen** [comment]
我有一个问题，我在运行了您的项目之后，发现我的左侧只有一个栏目，不清楚这是为什么

**Comment by zicla** [comment]
参考文档这里的步骤： https://tank-doc.eyeblue.cn/zh/basic/compile.html
