### ISSUE TITLE
install/index.vue在chrome更新密码时的问题

### ISSUE THREAD

**Issue by hffariel** [eyebluecn/tank-front#7]
如果在创建完管理员后，选择chrome的更新密码，那么前面的mysqlpassword会自动被chrome更新成adminpassword，是不是可以把index.vue中的mysqlpassword input加入autocomplete = 'new-password'属性，或者把httpFinish请求提前到上一步自动发起，而不是在点击返回首页时触发更好一些？

**Comment by zicla** [comment]
这个在最新版本中已经解决了这个问题，可以顺利完成安装。
