### ISSUE TITLE
elementui剥离

### ISSUE THREAD

**Issue by hffariel** [eyebluecn/tank-front#8]
是否可以吧elementui剥离出vendor，放到cdn更好些，现在vendor太大了，页面是否也可以改成require.ensure按需加载模式？移动端是否也可以加入-webkit-overflow-scrolling: touch;

**Comment by zicla** [comment]
1. 这个是开源软件，所以要做到尽量依赖最少，cdn也是一种依赖，因此不会主动放cdn。当然你可以把静态资源配置到cdn上。 2. 按需加载其实对性能提升很小，因为主要占空间的基础依赖，页面依赖非常小。 3. -webkit-overflow-scrolling: touch;这个可以考虑在下个版本加上。 如果速度比较慢，可以参考文档这里的cdn配置  https://tank-doc.eyeblue.cn/zh/advance/question.html

**Comment by gmugu** [comment]
> 1. 这个是开源软件，所以要做到尽量依赖最少，cdn也是一种依赖，因此不会主动放cdn。当然你可以把静态资源配置到cdn上。 2. 按需加载其实对性能提升很小，因为主要占空间的基础依赖，页面依赖非常小。 3. -webkit-overflow-scrolling: touch;这个可以考虑在下个版本加上。 如果速度比较慢，可以参考文档这里的cdn配置  https://tank-doc.eyeblue.cn/zh/advance/question.html

在https://tank-doc.eyeblue.cn/zh/advance/question.html上面找不到cdn配置的说明了，能否补充一下cdn配置的说明文档
